fix:issue-986
topcoder-platform/work-manager pull request #1028
Opened 2021-01-09 12:02 UTC by yoution

#986

2021-01-10 22:59 UTC, mflotynski commented on src/actions/challenges.js
> +    })
I think that it could be simplified without losing clarity:
```suggestion
    const promiseAll = groupIds.map(id => fetchGroupDetail(id));
```

2021-01-11 10:36 UTC, maxceem requested changes
@yoution the current fix has some issues.

If I create a challenge or update the challenge and go the view details page without page reloading the groups would not be shown, see demo video https://monosnap.com/file/oAMpt31iiCQ5mjHoLEE0DprDt2a8vb

This happens, because data is stored inside `challengeDetails` which is updated during challenge update. Please, don't store data there, as we would always lost it.

The best solution IMHO would be not to store groups in Redux store, and just create a hook, which would return group names by group ids, like `const goupsDetails = useGroupDetails(groupIds = [123, 435, 3453])`. Though it could be a little bit tricky to avoid unnecessary re-renders.

So storing in Redux store is also fine, but then we have to choose some new place for groups data which is not rewrtitten by other actions.

2021-01-11 10:44 UTC, maxceem commented
@yoution also, I've noticed that file `src/actions/challenges.js` has many unnecessary formatting changes. Please, don't make automatic formatted changes as we are doing several fixes in parallel, it could lead to the merge conflicts later. Update only the code which has to be updated for the issue.

2021-01-11 12:10 UTC, yoution commented
@maxceem please review

2021-01-11 20:32 UTC, maxceem approved these changes
Thanks, @yoution, works good now.

2021-01-11 20:32 UTC, merged